ktor:
  application:
    modules:
      - io.kops.webapp.ApplicationKt.module
  deployment:
    port: 8080
  koog:
    openrouter:
      apiKey: ${OPENROUTER_API_KEY}
      baseUrl: https://openrouter.ai