apiVersion: webapp.kops.io/v1alpha1
kind: WebappRepository
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: spring-petclinic
spec:
  serviceAccountName: kpack-service-account
  source:
    gitUrl: https://github.com/spring-projects/spring-petclinic
    revision: main
  build:
    - name: BP_JVM_VERSION
      value: "17"
  image:
    tag: frederikpietzko/spring-petclinic
  template:
    spec:
      ports:
        - "8080"
      ingress:
        host: testing.com
        path: "/*"

